services:
  # Новый сервис PHP
  php:
    image: php:8.2-fpm
    container_name: php_fpm
    restart: unless-stopped
    volumes:
      # Важно: пути здесь и в nginx должны совпадать, чтобы PHP видел те же файлы
      - ./www:/var/www/
    networks:
      - app_net

  nginx:
    build: ./docker/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/logs/nginx:/var/log/nginx
    depends_on:
      - php # Теперь nginx ждет запуска php
    networks:
      - app_net

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - NODE_ENV=production
    volumes:
      - ./data/n8n:/home/node/.n8n
    depends_on:
      - nginx
    networks:
      - app_net

networks:
  app_net:
    driver: bridge