services:
  # База данных
  db:
    image: mysql:8.0
    container_name: chat_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: minichat_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - app_net

  # Интерфейс для управления базой
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: chat_pma
    restart: unless-stopped
    ports:
      - "8081:80" # <-- Добавь это! Теперь PMA будет на порту 8081
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
    networks:
      - app_net
    depends_on:
      - db
  # Новый сервис PHP
  php:
    build: ./docker/php # Указываем путь к папке с твоим PHP Dockerfile
    container_name: php_fpm
    restart: unless-stopped
    volumes:
      - ./www:/var/www/
    networks:
      - app_net

  nginx:
    build: ./docker/nginx # Указываем путь к папке с твоим Nginx Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/logs/nginx:/var/log/nginx
    depends_on:
      - php
    networks:
      - app_net

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - NODE_ENV=production
    volumes:
      - ./data/n8n:/home/node/.n8n
    depends_on:
      - nginx
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
