# Это обязательный блок для работы процессов
events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Настройки логов
    access_log  /var/log/nginx/access.log;
    error_log   /var/log/nginx/error.log;

    # Подключаем твои настройки из папки conf.d
    # Именно здесь подхватится твой default.conf с прокси для n8n
    include /etc/nginx/conf.d/*.conf;
}