server {
    listen 80;
    server_name localhost;
    root /var/www/minichat; # Корень для файлов проекта minichat
    index index.php index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # --- ДОБАВЛЯЕМ ЭТОТ БЛОК ДЛЯ PHP ---
    location ~ \.php$ {
        fastcgi_pass php:9000; # Имя сервиса из docker-compose
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # Прокси для phpMyAdmin
    location /phpmyadmin {
        alias /var/www/localhost/phpmyadmin; # Путь к phpMyAdmin внутри контейнера
        index index.php;
        
        location ~ ^/phpmyadmin/(.+\.php)$ {
            try_files           $uri = 404;
            include             fastcgi_params;
            fastcgi_pass        phpmyadmin:9000;
            fastcgi_index       index.php;
            fastcgi_param       SCRIPT_FILENAME /var/www/html/$1;
	    }
       
	    location ~* ^/phpmyadmin/(.+\.(jpg|jpeg|gif|css|png|js|ico|html|xml|txt))$ {
            access_log off;
            log_not_found off;
            expires max;
	   }
    }
}